"""Curated list of uncensored and unrestricted open-source LLMs."""

from .registry import ModelEntry

UNCENSORED_MODELS = [
    ModelEntry(
        name="qwen2.5-coder-7b",
        repo_id="bartowski/Qwen2.5-Coder-7B-Instruct-GGUF",
        filename="Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf",
        size_gb=4.68, quantization="Q4_K_M", backend="llama_cpp",
        description="Qwen 2.5 Coder 7B — BEST coding model that fits 4GB VRAM. Top-tier code gen, editing, reasoning",
        context_length=32768, license="Apache-2.0",
        tags=["coding", "7b", "recommended", "best-quality"],
    ),
    ModelEntry(
        name="qwen2.5-coder-7b-q3",
        repo_id="bartowski/Qwen2.5-Coder-7B-Instruct-GGUF",
        filename="Qwen2.5-Coder-7B-Instruct-Q3_K_M.gguf",
        size_gb=3.66, quantization="Q3_K_M", backend="llama_cpp",
        description="Qwen 2.5 Coder 7B Q3 — smaller quant that fully fits in 4GB VRAM. Slightly lower quality",
        context_length=32768, license="Apache-2.0",
        tags=["coding", "7b", "4gb-vram", "fast"],
    ),
    ModelEntry(
        name="qwen2.5-coder-3b",
        repo_id="bartowski/Qwen2.5-Coder-3B-Instruct-GGUF",
        filename="Qwen2.5-Coder-3B-Instruct-Q4_K_M.gguf",
        size_gb=1.98, quantization="Q4_K_M", backend="llama_cpp",
        description="Qwen 2.5 Coder 3B — tiny, blazing fast on 4GB, surprisingly capable for its size",
        context_length=32768, license="Apache-2.0",
        tags=["coding", "3b", "fast", "4gb-vram", "lightweight"],
    ),
    ModelEntry(
        name="qwen2.5-coder-1.5b",
        repo_id="bartowski/Qwen2.5-Coder-1.5B-Instruct-GGUF",
        filename="Qwen2.5-Coder-1.5B-Instruct-Q4_K_M.gguf",
        size_gb=0.97, quantization="Q4_K_M", backend="llama_cpp",
        description="Qwen 2.5 Coder 1.5B — ultra-light for quick autocomplete, runs anywhere",
        context_length=32768, license="Apache-2.0",
        tags=["coding", "1.5b", "lightweight", "autocomplete"],
    ),
    ModelEntry(
        name="deepseek-coder-6.7b",
        repo_id="TheBloke/deepseek-coder-6.7B-instruct-GGUF",
        filename="deepseek-coder-6.7b-instruct.Q4_K_M.gguf",
        size_gb=4.09, quantization="Q4_K_M", backend="llama_cpp",
        description="DeepSeek Coder 6.7B — excellent code generation and completion, fits 4GB",
        context_length=16384, license="DeepSeek",
        tags=["coding", "6.7b", "completion", "good-quality"],
    ),
    ModelEntry(
        name="codellama-7b",
        repo_id="TheBloke/CodeLlama-7B-Instruct-GGUF",
        filename="codellama-7b-instruct.Q4_K_M.gguf",
        size_gb=4.09, quantization="Q4_K_M", backend="llama_cpp",
        description="CodeLlama 7B — Meta's coding model, solid all-around, fits 4GB",
        context_length=16384, license="Llama2",
        tags=["coding", "7b", "meta", "reliable"],
    ),
    ModelEntry(
        name="qwen2.5-coder-14b-q3",
        repo_id="bartowski/Qwen2.5-Coder-14B-Instruct-GGUF",
        filename="Qwen2.5-Coder-14B-Instruct-Q3_K_M.gguf",
        size_gb=7.7, quantization="Q3_K_M", backend="llama_cpp",
        description="Qwen 2.5 Coder 14B Q3 — higher quality but needs offload; use on cloud or bigger GPU",
        context_length=32768, license="Apache-2.0",
        tags=["coding", "14b", "high-quality", "cloud"],
    ),
    ModelEntry(
        name="mistral-7b-instruct",
        repo_id="TheBloke/Mistral-7B-Instruct-v0.2-GGUF",
        filename="mistral-7b-instruct-v0.2.Q4_K_M.gguf",
        size_gb=4.37, quantization="Q4_K_M", backend="llama_cpp",
        description="Mistral 7B Instruct — fast, capable, uncensored fine-tune",
        context_length=32768, license="Apache-2.0",
        tags=["7b", "instruct", "fast", "general"],
    ),
    ModelEntry(
        name="openhermes-7b",
        repo_id="TheBloke/OpenHermes-2.5-Mistral-7B-GGUF",
        filename="openhermes-2.5-mistral-7b.Q4_K_M.gguf",
        size_gb=4.37, quantization="Q4_K_M", backend="llama_cpp",
        description="OpenHermes 2.5 — uncensored, excellent for coding and reasoning",
        context_length=8192, license="OpenRAIL-M",
        tags=["7b", "coding", "reasoning", "uncensored"],
    ),
    ModelEntry(
        name="dolphin-2.2.1-mistral-7b",
        repo_id="TheBloke/dolphin-2.2.1-mistral-7B-GGUF",
        filename="dolphin-2.2.1-mistral-7b.Q4_K_M.gguf",
        size_gb=4.37, quantization="Q4_K_M", backend="llama_cpp",
        description="Dolphin 2.2.1 — explicitly uncensored, no alignment",
        context_length=8192, license="MIT",
        tags=["7b", "uncensored", "unfiltered", "general"],
    ),
    ModelEntry(
        name="neural-chat-7b",
        repo_id="TheBloke/neural-chat-7B-v3.1-GGUF",
        filename="neural-chat-7b-v3.1.Q4_K_M.gguf",
        size_gb=4.37, quantization="Q4_K_M", backend="llama_cpp",
        description="Intel Neural Chat 7B — conversational, capable, less restrictive",
        context_length=8192, license="Apache-2.0",
        tags=["7b", "chat", "conversational"],
    ),
    ModelEntry(
        name="airoboros-mistral-7b",
        repo_id="TheBloke/Airoboros-Mistral-7B-GGUF",
        filename="airoboros-mistral-7b.Q4_K_M.gguf",
        size_gb=4.37, quantization="Q4_K_M", backend="llama_cpp",
        description="Airoboros — uncensored, roleplay and creative writing focused",
        context_length=8192, license="MIT",
        tags=["7b", "roleplay", "creative", "uncensored"],
    ),
    ModelEntry(
        name="zephyr-7b-beta",
        repo_id="TheBloke/zephyr-7B-beta-GGUF",
        filename="zephyr-7b-beta.Q4_K_M.gguf",
        size_gb=4.37, quantization="Q4_K_M", backend="llama_cpp",
        description="Zephyr 7B Beta — aligned but highly capable, good general purpose",
        context_length=8192, license="MIT",
        tags=["7b", "general", "aligned"],
    ),
    ModelEntry(
        name="llama-3-8b-instruct",
        repo_id="QuantFactory/Meta-Llama-3-8B-Instruct-GGUF",
        filename="Meta-Llama-3-8B-Instruct.Q4_K_M.gguf",
        size_gb=4.92, quantization="Q4_K_M", backend="llama_cpp",
        description="Llama 3 8B Instruct — Meta's latest, highly capable",
        context_length=8192, license="Meta-Llama-3",
        tags=["8b", "instruct", "latest", "general"],
    ),
    ModelEntry(
        name="solar-10.7b-instruct",
        repo_id="TheBloke/Solar-10.7B-Instruct-v1.0-GGUF",
        filename="solar-10.7b-instruct-v1.0.Q4_K_M.gguf",
        size_gb=6.46, quantization="Q4_K_M", backend="llama_cpp",
        description="Solar 10.7B — Korean-made, excellent multilingual, less censored",
        context_length=4096, license="Apache-2.0",
        tags=["10b", "multilingual", "capable"],
    ),
]
